from __future__ import annotations

import argparse
import io
import re
import tokenize
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple


EMOJI_REPLACEMENTS = {
    "🚨": "[ALERTA]",
    "✅": "[OK]",
    "❌": "[ERRO]",
    "📌": "[PONTO]",
    "🔢": "[NUMERO]",
    "🕐": "[HORARIO]",
}

ARROW_REPLACEMENTS = {
    "→": "->",
    "←": "<-",
    "⇒": "=>",
    "⟶": "->",
}

DECORATIVE_SYMBOLS = set("●◆▶★✦•")
SEPARATOR_CHARS = set("─═━")
BOX_BORDER_CHARS = set("╔╗╚╝║╠╣╦╩╬┌┐└┘│┬┴├┤┼")

SKIP_DIR_NAMES = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "tests",
    "test",
    "migrations",
    "migration",
    "alembic",
    "build",
    "dist",
}

SKIP_FILE_PATTERNS = (
    "test_*.py",
    "*_test.py",
    "*_pb2.py",
    "*_generated.py",
)


@dataclass
class Change:
    file: str
    line: int
    removed: str
    replaced: str


def _looks_generated(path: Path, text: str) -> bool:
    lowered = text[:2000].lower()
    return (
        "auto-generated" in lowered
        or "autogenerated" in lowered
        or "generated file" in lowered
        or "do not edit" in lowered
    )


def _should_skip(path: Path, root: Path) -> bool:
    rel = path.relative_to(root)
    if any(part.lower() in SKIP_DIR_NAMES for part in rel.parts):
        return True
    return any(path.match(pattern) for pattern in SKIP_FILE_PATTERNS)


def _build_line_offsets(text: str) -> List[int]:
    offsets = [0]
    running = 0
    for line in text.splitlines(keepends=True):
        running += len(line)
        offsets.append(running)
    if not text.endswith(("\n", "\r")):
        offsets.append(len(text))
    return offsets


def _to_offset(line_offsets: Sequence[int], line: int, col: int) -> int:
    return line_offsets[line - 1] + col


def _replace_separator_runs(value: str) -> str:
    return re.sub(r"[─═━]{3,}", "------------", value)


def _clean_char(
    ch: str,
    *,
    in_comment: bool,
) -> str:
    if ch in EMOJI_REPLACEMENTS:
        return EMOJI_REPLACEMENTS[ch]
    if ch in ARROW_REPLACEMENTS:
        return ARROW_REPLACEMENTS[ch]
    if ch in DECORATIVE_SYMBOLS:
        return ""
    if ch in BOX_BORDER_CHARS:
        return ""
    if in_comment and ch in SEPARATOR_CHARS:
        return "-"
    if ord(ch) > 127:
        return ""
    return ch


def _clean_token_value(value: str, *, in_comment: bool) -> Tuple[str, List[Tuple[str, str]]]:
    if in_comment:
        value = _replace_separator_runs(value)

    out: List[str] = []
    replacements: List[Tuple[str, str]] = []
    for ch in value:
        new_ch = _clean_char(ch, in_comment=in_comment)
        if new_ch != ch:
            replacements.append((ch, new_ch))
        out.append(new_ch)
    return "".join(out), replacements


def _clean_string_token(token_value: str) -> Tuple[str, List[Tuple[str, str]]]:
    try:
        parsed = ast_literal_eval_string(token_value)
    except Exception:
        cleaned, repl = _clean_token_value(token_value, in_comment=False)
        return cleaned, repl

    cleaned_content, replacements = _clean_token_value(parsed["content"], in_comment=False)
    if cleaned_content == parsed["content"]:
        return token_value, []
    rebuilt = f"{parsed['prefix']}{parsed['quote']}{cleaned_content}{parsed['quote']}"
    return rebuilt, replacements


def ast_literal_eval_string(token_value: str) -> dict:
    i = 0
    while i < len(token_value) and token_value[i] in "rRuUbBfF":
        i += 1
    prefix = token_value[:i]
    body = token_value[i:]

    if body.startswith("\"\"\"") and body.endswith("\"\"\"") and len(body) >= 6:
        return {"prefix": prefix, "quote": "\"\"\"", "content": body[3:-3]}
    if body.startswith("'''") and body.endswith("'''") and len(body) >= 6:
        return {"prefix": prefix, "quote": "'''", "content": body[3:-3]}
    if body.startswith("\"") and body.endswith("\"") and len(body) >= 2:
        return {"prefix": prefix, "quote": "\"", "content": body[1:-1]}
    if body.startswith("'") and body.endswith("'") and len(body) >= 2:
        return {"prefix": prefix, "quote": "'", "content": body[1:-1]}

    raise ValueError("string token format not supported")


def _apply_edits(text: str, edits: Sequence[Tuple[int, int, str]]) -> str:
    if not edits:
        return text
    chunks = []
    cursor = 0
    for start, end, new_value in sorted(edits, key=lambda e: e[0]):
        chunks.append(text[cursor:start])
        chunks.append(new_value)
        cursor = end
    chunks.append(text[cursor:])
    return "".join(chunks)


def clean_file(path: Path, root: Path) -> Tuple[bool, List[Change]]:
    text = path.read_text(encoding="utf-8")
    if _looks_generated(path, text):
        return False, []

    line_offsets = _build_line_offsets(text)
    changes: List[Change] = []
    edits: List[Tuple[int, int, str]] = []

    stream = io.StringIO(text)
    for token in tokenize.generate_tokens(stream.readline):
        token_type = token.type
        if token_type not in (tokenize.COMMENT, tokenize.STRING):
            continue

        old_value = token.string
        if token_type == tokenize.COMMENT:
            new_value, replacements = _clean_token_value(old_value, in_comment=True)
        else:
            new_value, replacements = _clean_string_token(old_value)

        if new_value == old_value:
            continue

        start_off = _to_offset(line_offsets, token.start[0], token.start[1])
        end_off = _to_offset(line_offsets, token.end[0], token.end[1])
        edits.append((start_off, end_off, new_value))

        for removed, replaced in replacements:
            changes.append(
                Change(
                    file=str(path.relative_to(root)).replace("\\", "/"),
                    line=token.start[0],
                    removed=removed,
                    replaced=replaced,
                )
            )

    if not edits:
        return False, []

    updated = _apply_edits(text, edits)
    if updated != text:
        path.write_text(updated, encoding="utf-8", newline="")
        return True, changes

    return False, []


def iter_python_files(root: Path) -> Iterable[Path]:
    for path in root.rglob("*.py"):
        if _should_skip(path, root):
            continue
        yield path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Limpa caracteres nao-ASCII/decorativos em arquivos Python do projeto.",
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Diretorio raiz do projeto (padrao: diretorio atual).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Somente mostra as mudancas sem gravar arquivos.",
    )
    parser.add_argument(
        "--report-file",
        default="",
        help="Arquivo para salvar o relatorio (opcional).",
    )
    args = parser.parse_args()

    root = Path(args.root).resolve()
    files = list(iter_python_files(root))

    processed_files = 0
    all_changes: List[Change] = []
    touched_files: List[Tuple[Path, str]] = []

    for path in files:
        original_text = path.read_text(encoding="utf-8")
        changed, changes = clean_file(path, root)
        if changed:
            processed_files += 1
            all_changes.extend(changes)
            touched_files.append((path, original_text))

    if args.dry_run:
        for path, content in touched_files:
            path.write_text(content, encoding="utf-8", newline="")

    report_lines: List[str] = []
    for change in all_changes:
        replaced_display = change.replaced if change.replaced else "<REMOVIDO>"
        report_lines.append(
            f"[ARQUIVO] {change.file} | [LINHA] {change.line} | "
            f"[REMOVIDO] {change.removed} | [SUBSTITUIDO POR] {replaced_display}"
        )

    report_lines.append(
        f"Contagem final: {processed_files} arquivos processados, "
        f"{len(all_changes)} substituicoes feitas"
    )

    for line in report_lines:
        print(line)

    if args.report_file:
        report_path = (root / args.report_file).resolve()
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text("\n".join(report_lines) + "\n", encoding="utf-8", newline="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())